version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: abl_com_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hassan1234
      POSTGRES_DB: ablmuawin_data_collection
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build:
      context: .
    container_name: ABL_COM_ABL_Muawin_Chatbot
    depends_on:
      - postgres
    environment:
        DATABASE_URL: postgresql://postgres:hassan1234@postgres:5432/ablmuawin_data_collection

    ports:
      - "8000:8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  postgres_data:
